version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    docker:
      - image: 'cimg/node:16.16.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm install -g gatsby-cli
      - run:
          command: npm test

workflows:
  node_tests:
    jobs:
      - test
